services:
  - type: web
    name: smart-it-tracker-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://your-frontend-url.onrender.com
      - key: DB_HOST
        value: your-postgres-host
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: smart_it_tracker
      - key: DB_USER
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
      - key: JWT_SECRET
        value: your-jwt-secret
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: your-email@gmail.com
      - key: SMTP_PASS
        value: your-app-password
      - key: OPENAI_API_KEY
        value: your-openai-api-key
